"""empty message

Revision ID: 34847935cd7c
Revises: e830e06f4eba
Create Date: 2016-06-13 15:10:24.194672

"""

# revision identifiers, used by Alembic.
revision = '34847935cd7c'
down_revision = 'e830e06f4eba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('afterschool_programs', 'estimated',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('afterschool_programs', 'lat',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('afterschool_programs', 'lon',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('afterschool_programs', 'lon',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('afterschool_programs', 'lat',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('afterschool_programs', 'estimated',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    ### end Alembic commands ###
