"""empty message

Revision ID: 8a7cec72fc68
Revises: 97bb0a2ee4b4
Create Date: 2016-05-24 16:06:30.191256

"""

# revision identifiers, used by Alembic.
revision = '8a7cec72fc68'
down_revision = '97bb0a2ee4b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afterschool_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('setting', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afterschool_programs')
    ### end Alembic commands ###
