"""empty message

Revision ID: 97bb0a2ee4b4
Revises: None
Create Date: 2016-05-24 16:01:35.516277

"""

# revision identifiers, used by Alembic.
revision = '97bb0a2ee4b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afterschool_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('setting', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afterschool_programs')
    ### end Alembic commands ###
