"""empty message

Revision ID: e830e06f4eba
Revises: None
Create Date: 2016-05-24 18:46:29.132861

"""

# revision identifiers, used by Alembic.
revision = 'e830e06f4eba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afterschool_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academics', sa.Boolean(), nullable=True),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('agency_tel', sa.String(), nullable=True),
    sa.Column('arts_culture', sa.Boolean(), nullable=True),
    sa.Column('cbo_service', sa.String(), nullable=True),
    sa.Column('cbo_sp_tel', sa.String(), nullable=True),
    sa.Column('elementary', sa.Boolean(), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('estimated', sa.Integer(), nullable=True),
    sa.Column('evenings', sa.Boolean(), nullable=True),
    sa.Column('high_school', sa.Boolean(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('middle_school', sa.Boolean(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.Column('program_ty', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('school_year', sa.Boolean(), nullable=True),
    sa.Column('setting', sa.String(), nullable=True),
    sa.Column('site_borough', sa.String(), nullable=True),
    sa.Column('site_building', sa.String(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('site_street', sa.String(), nullable=True),
    sa.Column('site_zip', sa.Integer(), nullable=True),
    sa.Column('sp_ein', sa.Integer(), nullable=True),
    sa.Column('sports_phy', sa.Boolean(), nullable=True),
    sa.Column('summer', sa.Boolean(), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.Column('weekends', sa.Boolean(), nullable=True),
    sa.Column('weekly_hours', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afterschool_programs')
    ### end Alembic commands ###
